# Generated by Django 5.2.9 on 2025-12-21 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('job_seeker', 'Job Seeker'), ('joiner', 'Joiner'), ('part_time', 'Part Time'), ('employer', 'Employer'), ('freelancer', 'Freelancer')], max_length=20),
        ),
    ]
