# Generated by Django 5.2.9 on 2026-01-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reference_code',
            field=models.CharField(blank=True, help_text='Optional reference code', max_length=50, null=True),
        ),
    ]
